config/routes.rb
Rails.application.routes.draw do
  get 'react',       to: 'react#index'
  get 'react/*path', to: 'react#index'

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :characters, expect: %i[new edit]
    end
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  # Validators
  validates :name,
            presence: true
end

app/controllers/api/v1/characters_controller.rb
class Api::V1::CharactersController < ApplicationController
  before_action :set_character, only: %i[show update destroy]

  respond_to :json

  def index
    @characters = Character.all.order(name: :asc)
    respond_with @characters
  end

  def show
    respond_with @character
  end

  def create
    @character = Character.create(character_params)
    render json: @character.errors, status: :unprocessable_entity unless @character.save
    respond_with @character
  end

  def update
    unless @character.update(character_params)
      render json: @character.errors,
             status: :unprocessable_entity
    end
    respond_with @character
  end

  def destroy
    @character.destroy
    respond_with @character
  end

  private

  def set_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/react_controller.rb
class ReactController < ApplicationController
  layout 'react_application'

  def index
  end
end

app/helpers/api/v1/characters_helper.rb
module Api::V1::CharactersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/react_helper.rb
module ReactHelper
end

app/views/home/index.html.haml
%header
  %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
    .container.px-5
      = link_to 'Rails test', root_path, class: 'navbar-brand'
      %button.navbar-toggler{type: "button",
        'data-bs-toggle' => "collapse",
        'data-bs-target' => "#navbarSupportedContent",
        'aria-controls' => "navbarSupportedContent",
        'aria-expanded' => "false",
        'aria-label' => "Toggle navigation"}
        %span.navbar-toggler-icon
      .collapse.navbar-collapse.collapse#navbarSupportedContent
        %ul.navbar-nav.ms-auto.mb-2.mb-lg-0
          %li.nav-item
            = link_to 'react', react_path, class: 'nav-link'
          %li.nav-item
            = link_to 'dummy', root_path, class: 'nav-link'

.container.px-4.px-lg-5
  .row.gx-4.gx-lg-5.align-items-center.my-5
    %h1.font-weight-light Home
    %p
      Home画面です

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsDemosite
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

  %body
    = yield

app/views/layouts/react_application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsDemosite
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'react_application'

  %body
    = yield

app/views/react/index.html.haml
= react_component('index')